### PR TITLE
Quest Books Rewrite

### LINKED ISSUE #144: Naquadah Reactor MK1 & MK2 quest inconsitency
**Pack Version:**
1.4.1a

**Description:**
Naquadah Reactor MK1 quest requires 3 omnium trimmed blocks of black steel, but the reactor itself calls for only 1, plus 2 blocks of duranium (not listed as a quest requirement)

Naquadah Reactor MK2 quest requires 5 blocks of omnium, reactor itself only calls for 1, plus 3 blocks of ruthenium trinium americium neutronate (not listed as quest requirement)

**Expected Behavior:**
Quest book requirements should match what is required to create the reactors. Currently if following the quest book you have the wrong materials and unable to make reactors.

**Steps To Reproduce:**
View Naquadah Reactor MK1 and MK2 quests under "Late Game" tab of quest book

**Crash Log:**
N/A
**Screenshots:**

### LINKED ISSUE #150: (hard mode) backwards quest dependency
Playing v1.4.2 on curseforge, hard mode

I'm at the point of building my first mk2 fusion reactor, and I noticed that some of the quests have dependencies in the wrong order, I think due to the cleanroom change.

In particular the wetware circuits require a sterilized cleanroom, which requires tritanium, which requires a mk2 fusion reactor. But the quest for the mk2 fusion reactor is locked behind the wetware circuits rather than the other way around.

As far as I can tell this is just a quest issue, not an actual progression issue -- I haven't finished building the mk2 fusion reactor but so far I haven't seen anything that requires wetware circuits / components. It's just a minor annoyance that I don't get to read the quest description while building the reactor, and I am not sure if I'll have to go back and re-complete it later.

### LINKED ISSUE #162: "Explore Actually Additions" Quest references unobtainable "Vertical digger"
**Pack Version:**
1.5

**Description:**
The "Explore Actually Additions" Quest references the "Vertical Digger" which is unobtainable and probably got replaced by GT miners.

**Expected Behavior:**
Just don't talk about it.

**Steps To Reproduce:**
Open Questbook, unlock all quests, look at the Explore Actually Additions Quest

**Screenshots:**

grafik

### LINKED ISSUE #174: Sodium perfulfate and iron III chloride quest
The quest talks about how it's my choice to use either this or that and if I'm taking the iron III route I'm not going to make sodium persulfate ever, so the quest should be to submit either one, not both.

### PR DESCRIPTION
**Pull request by IntegerLimit**
Check each individual commit for information.
Fixes #144 
Fixes #162
Fixes #150
Fixes #174 
Supersedes #148 
Hard mode edits will not be as detailed and focused as Normal Mode, due to lack of time and experience with Hard Mode.

### CODE REVIEW

**Comment by IntegerLimit** [comment]
Closes Issue #144

**Comment by IntegerLimit** [comment]
Because of uploading HM Quest json into both places, this now supersedes #148

**Comment by IntegerLimit** [comment]
The main correcting part of this PR is now complete. If time is not sufficient, it can be merged now.
However, I would like to add a Processing Lines chapter. Therefore, unless time is not sufficient, this PR will not be marked as complete.

**Comment by CrossElectronics** [comment]
As for 1.4.2, the hard mode quest "Cleanroom" is not implemented, can you try fixing? Thanks!

**Comment by IntegerLimit** [comment]
> As for 1.4.2, the hard mode quest "Cleanroom" is not implemented, can you try fixing? Thanks!

Alright.

**Comment by IntegerLimit** [comment]
> As for 1.4.2, the hard mode quest "Cleanroom" is not implemented, can you try fixing? Thanks!

Done. Commit https://github.com/tracer4b/nomi-ceu/pull/152/commits/56b7c2d20dfc75d658ca4f3053fba9647f9ae9f7

**Comment by IntegerLimit** [comment]
Ready to merge. More changes coming later.

**Pull request merged**
